asset:
  name: csv_product
  source_type: csv
  object: Product
  version: "1.0"

  schema:
    - name: ProductID
      type: integer
      required: true
    - name: Name
      type: string
      required: true
    - name: ProductNumber
      type: string
      required: true
    - name: MakeFlag
      type: integer
      required: true
    - name: FinishedGoodsFlag
      type: integer
      required: true
    - name: Color
      type: string
      required: false
    - name: SafetyStockLevel
      type: integer
      required: true
    - name: ReorderPoint
      type: integer
      required: true
    - name: StandardCost
      type: double
      required: true
    - name: ListPrice
      type: double
      required: true
    - name: Size
      type: string
      required: false
    - name: SizeUnitMeasureCode
      type: string
      required: false
    - name: WeightUnitMeasureCode
      type: string
      required: false
    - name: Weight
      type: double
      required: false
    - name: DaysToManufacture
      type: integer
      required: true
    - name: ProductLine
      type: string
      required: false
    - name: Class
      type: string
      required: false
    - name: Style
      type: string
      required: false
    - name: ProductSubcategoryID
      type: integer
      required: false
    - name: ProductModelID
      type: integer
      required: false
    - name: SellStartDate
      type: timestamp
      required: true
    - name: SellEndDate
      type: timestamp
      required: false
    - name: DiscontinuedDate
      type: timestamp
      required: false
    - name: rowguid
      type: string
      required: true
    - name: ModifiedDate
      type: timestamp
      required: true

  governance:
    owner: data-team@company.com
    cost_center: FIN-PROD-004
    tags: [adventureworks, product, test-data]
    classification: [INTERNAL]
    retention_days: 365

  lineage:
    - from_asset: source.erp.adventureworks_product
      to_asset: csv_product
      contract_version: "1.0"
      description: Nightly export from ERP to curated product asset

  audit:
    - author: data-team@company.com
      change_type: initial_publish
      timestamp: 2025-01-08T08:00:00Z
      hash: 9f5a1c3d7e8b2f4a6c1d3e5f7a9b0c2d4e6f8091a2b3c4d5e6f708192a3b4c5

  target:
    file_format: parquet
    partitioning: [ingest_date]
    mode: strict
