$schema: schemas/odcs/dativo-odcs-3.0.2-extended.schema.json
apiVersion: v3.0.2
kind: DataContract
name: google_sheets_sheet
version: "1.0"
source_type: google_sheets
object: sheet

schema:
  - name: id
    type: string
    required: true
  - name: spreadsheetId
    type: string
    required: false
  - name: modifiedTime
    type: timestamp
    required: false

team:
  owner: data-team@company.com

tags: [files, sheets]

compliance:
  classification: []
  retention_days: 90

target:
  file_format: parquet
  partitioning: [ingest_date]
  mode: strict
