$schema: schemas/odcs/dativo-odcs-3.0.2-extended.schema.json
apiVersion: v3.0.2
kind: DataContract
id: 550e8400-e29b-41d4-a716-446655440001
name: markdown_kv_lines
version: "1.0"
status: active
domain: dativo
dataProduct: markdown_kv
tenant: test_tenant
description:
  purpose: "Row-per-KV storage pattern for Markdown-KV format - flattened, query-friendly structure"
  limitations: "Reconstructing full documents requires grouping by doc_id and section"
  usage: "Ideal for filtering and joining operations (e.g., 'all docs where model:: gpt-4')"
tags: [markdown-kv, llm, structured-data, row-per-kv]

# Dativo extensions
source_type: markdown_kv
object: md_kv_lines
target:
  file_format: parquet
  partitioning: [ingest_date]
  mode: strict

schema:
  - name: doc_id
    type: string
    required: true
    description: "Document identifier"
  
  - name: section
    type: string
    required: false
    description: "Section name (from Markdown headers or '_front_matter')"
  
  - name: key
    type: string
    required: true
    description: "Key from key-value pair"
  
  - name: value
    type: string
    required: false
    description: "Value from key-value pair (string representation)"
  
  - name: value_json
    type: string
    required: false
    description: "JSON-serialized value for complex types (dicts, arrays)"
  
  - name: ord
    type: integer
    required: false
    description: "Display order within section (preserves original order)"
  
  - name: extracted_at
    type: timestamp
    required: false
    description: "Timestamp when the key-value pair was extracted"
  
  - name: ingest_date
    type: date
    required: false
    description: "Date of ingestion (for partitioning)"

data_quality:
  expectations: []
  monitoring:
    enabled: true
    oncall_rotation: data-ops-oncall@company.com
  alerts:
    channels: [slack, email]
    thresholds: {}

team:
  owner: data-team@company.com
  cost_center: FIN-DOCS-008
  roles:
    - name: Data Engineer
      email: engineer@company.com
      responsibility: ingestion

compliance:
  classification: [DOCUMENTATION]
  regulations: []
  retention_days: 365
  security:
    access_control: role_based
    encryption_required: true
  user_consent_required: false

change_management:
  policy: non-breaking
  approval_required: true
  notification_channels: [slack, email]
  version_history: true

lineage:
  - from_asset: source.docs.markdown_repository
    to_asset: markdown_kv_lines
    contract_version: "1.0"
    description: Markdown sections exploded into row-per-KV analytic table

audit:
  - author: data-team@company.com
    change_type: initial_publish
    timestamp: 2025-01-04T05:00:00Z
    hash: 2234567890abcdef1234567890abcdef1234567890abcdef1234567890abcd

