# Multi-tenant deployment with shared infrastructure
# This example demonstrates how to use shared infrastructure with tenant isolation

tenant_id: "${TENANT_ID}"  # Dynamic tenant ID from environment
environment: prod

# Connector paths
source_connector: stripe
source_connector_path: /app/connectors/stripe.yaml
target_connector: iceberg
target_connector_path: /app/connectors/iceberg.yaml

# Asset definition
asset: stripe_customers
asset_path: /app/assets/stripe/v1.0/customers.yaml

# Source configuration
source:
  objects: [customers]
  incremental:
    strategy: updated_at
    cursor_field: updated
    lookback_days: 1

# Target configuration with tenant-specific paths
target:
  branch: "${TENANT_ID}"
  warehouse: "s3://dativo-shared-data-lake/${TENANT_ID}/"
  connection:
    nessie:
      uri: "${NESSIE_URI}"
    s3:
      bucket: dativo-shared-data-lake
      prefix: "${TENANT_ID}/raw/stripe/customers"

# Shared infrastructure with tenant isolation
infrastructure:
  provider: aws
  
  # Shared runtime with tenant-specific namespace
  runtime:
    type: ecs
    cluster_name: dativo-shared-prod-cluster
    namespace: "${TENANT_ID}-etl"  # Logical isolation per tenant
    service_account: "arn:aws:iam::123456789012:role/dativo-${TENANT_ID}-etl-role"
  
  # Compute resources (consistent across tenants)
  compute:
    cpu: "2048"
    memory: "4096"
    instance_type: t3.medium
    max_runtime_seconds: 3600
  
  # Shared networking
  networking:
    vpc_id: vpc-shared
    subnet_ids:
      - subnet-shared-private-1a
      - subnet-shared-private-1b
    security_group_ids:
      - sg-shared-etl
    private_networking: true
  
  # Tenant-specific storage paths
  storage:
    bucket: dativo-shared-data-lake
    prefix: "${TENANT_ID}/raw/stripe/customers"
    kms_key_id: arn:aws:kms:us-east-1:123456789012:key/shared-etl-key
  
  # Tags with tenant identification
  tags:
    Tenant: "${TENANT_ID}"
    CostCenter: "SHARED-DATA-001"
    Project: data-platform
    Environment: production
    ManagedBy: terraform
    SharedInfrastructure: "true"
  
  # Terraform module with tenant-specific variables
  terraform:
    module_source: git::https://github.com/acme/terraform-dativo-aws.git//modules/ecs-dagster-shared
    module_version: "1.2.0"
    workspace: "shared-prod"
    backend_config:
      bucket: acme-terraform-state
      key: "dativo/shared/etl-jobs/${TENANT_ID}/stripe-customers.tfstate"
      region: us-east-1
    variables:
      tenant_id: "${TENANT_ID}"
      enable_monitoring: true
      enable_tenant_isolation: true
  
  # Dagster configuration
  dagster:
    code_location: dativo-etl-shared-prod
    repository: etl_jobs
    resource_requirements:
      request_cpu: "2048"
      request_memory: "4096"
      limit_cpu: "4096"
      limit_memory: "8192"

# FinOps metadata with tenant tracking
finops:
  cost_center: SHARED-DATA-001
  business_tags:
    - payments
    - revenue
    - stripe
    - shared-infrastructure
  project: data-platform
  environment: production

# Retry configuration
retry_config:
  max_attempts: 3
  initial_delay_seconds: 10
  max_delay_seconds: 300
  backoff_multiplier: 2.0

# Logging configuration
logging:
  level: INFO
  redaction: true
